### ISSUE TITLE
Please install edgar.appdata.xml.in

### ISSUE THREAD

**Issue by nemysis** [riksweeney/edgar#1]
Hello I'm openSUSE and FreeBSD maintainer for The Legend of Edgar and more others Yours games :)

https://build.opensuse.org/package/show/home:nemysis:branches:games/edgar

https://www.freshports.org/games/legend-of-edgar/

I see in sources

```
icons/edgar.appdata.xml.in
```

but is not installed, please change makefile.

**Comment by riksweeney** [comment]
Just to confirm, this file should be installed to /usr/share/appdata/edgar.appdata.xml is that correct?

**Comment by nemysis** [comment]
Yes this is right

```
/usr/share/appdata/edgar.appdata.xml
```

And add also how is to update mime database.

Thanks.

**Comment by riksweeney** [comment]
Sorry, I don't understand what you mean regarding the mime database, do you want me to also run the update-mime-database command? Is this required for openSUSE and FreeBSD?

**Comment by nemysis** [comment]
Yes is important in openSUSE and FreeBSD I have think on this or similar

```
%post
update-mime-database %{_datadir}/mime

%postun
update-mime-database %{_datadir}/mime
```

This is similar than for Desktop entry file which i use for Edgar in openSUSE

```
%if 0%{?suse_version}
    %suse_update_desktop_file %{name}
    %fdupes -s %{buildroot}%{_prefix}
%endif
```

**Comment by akien-mga** [comment]
This is not a MIME type definition, so nothing is required regarding the MIME database.
Even if it were, it's usually the packager's job to do this kind of thing, and should not be done in the upstream Makefile.
