### ISSUE TITLE
Medal table doesn't work properly

### ISSUE THREAD

**Issue by yarnweaver** [riksweeney/edgar#13]
The medal table only opens correctly when opened for the first time after launching the application.
Upon opening it a second or subsequent time, it cannot be scrolled all the way down to the bottom. The furthest down that it will go, is the medal for defeating the Borer.

Medals are still correctly credited, though - and any that cannot be viewed in-game, become viewable upon quitting and relaunching the game application.

**Comment by riksweeney** [comment]
Thanks for the report.
