### ISSUE TITLE
version 1.27 - seven-stage Gargoyle battle, can get stuck in transition from third to fourth stage

### ISSUE THREAD

**Issue by yarnweaver** [riksweeney/edgar#24]
The Gargoyle boss fight has seven stages, in which Gargoyle has a range of attacks during the first, third and fifth stages, and in which Edgar attacks spears on the drawbridge during the second, fourth and sixth stages. Bringing Gargoyle's health down to a quarter in the first, third or fifth stage will initiate the subsequent stage.

One of Gargoyle's attacks in the third stage is to drop a spear to create a hole in the drawbridge that Edgar could fall through. However, if Gargoyle is positioned above this hole at the transition to the fourth stage, and drops the spear over the hole, Gargoyle gets stuck. Gargoyle stops attacking Edgar, and it seems that Edgar cannot do any attacks that will either damage Gargoyle, or which will move the battle onto stage five.

I've never noticed this prior to version 1.27 - however, in version 1.27, Gargoyle is lower and easier for Edgar to attack during Gargoyle's spear-dropping-hole-creating attack, so I guess the scenario is more likely to arise in version 1.27 than earlier versions.

**Comment by riksweeney** [comment]
Thanks for the report
