### ISSUE TITLE
Porting to SDL2

### ISSUE THREAD

**Issue by raptor** [riksweeney/edgar#3]
Hi, I was wondering if you have considered porting edgar to SDL 2.0.  This would bring some advantages like better OSX/Linux window support (e.g. allow alt-tab) as well as some better compatibility with other and newer platforms.

I have some experience porting from SDL 1.2 to 2.0 and may be able to help out a little.

Thanks!

**Comment by riksweeney** [comment]
I've thought about updating it to SDL 2, but I'm currently in no rush to do so. Maybe I'll look into doing so next year.

**Comment by Ferk** [comment]
Maybe SDL 2 would make an hypothetical android port more viable.
It would be awesome to be able to play edgar on the phone.
