### ISSUE TITLE
Mistype in dialogue in village

### ISSUE THREAD

**Issue by Arcanister** [riksweeney/edgar#44]
When you talk with Maggi with LC_ALL set to ru_RU.UTF-8, you get Борган in yellow (Borgan) instead of Мэгги (Maggi) as title of dialogue where she says hello.
I didn't check in English locale yet.

**Comment by riksweeney** [comment]
Can you post a screenshot? I don't get this bug.

![edgar](https://user-images.githubusercontent.com/12698517/61316719-7ac5f600-a7f9-11e9-8a79-2bfea4442bd5.png)

**Comment by Arcanister** [comment]
I have been able to reproduce it. First of all, it works both ways, it seems. If I first go to Maggie, then dialogue with Borgan will be botched and if I first go to Borgan then dialogue with Borgan will be OK and dialogue with Maggie botched. 
Second, it works same with English locale.

Here is a screenshot:
![Edgar-dialog-bug-Borgan-ru](https://user-images.githubusercontent.com/31947120/61428808-5e8b9b80-a956-11e9-99ab-8f6290794325.png)
