### ISSUE TITLE
Edgar 1.32 and 1.33 compiled for 64-bit Windows only

### ISSUE THREAD

**Issue by JohnTHaller** [riksweeney/edgar#46]
It seems that 1.32 and 1.33 are compiled for 64-bit Windows, while 1.31 was compiled for 32-bit. While 1.31 runs on all Windows machines, 1.32 and 1.33 won't run on 32-bit Windows machines (Win7-Win10) nor will they run on Windows ARM machines like the new Microsoft Surface Pro X (it can only run 32-bit x86 apps). Is there any reason for the change? Can we get a 32-bit build as well?

**Comment by riksweeney** [comment]
I'll have another look and see if I can get the resources needed to compile the game for 32 bit Windows. I remember not having much luck in the past. I can't promise anything though as support for 32 bit is slowly being phased out.

**Comment by riksweeney** [comment]
I've tried to compile a 32bit version of the game for Windows. You can try the installer here and let me know how you get on.

https://www.dropbox.com/sh/qs2gu74802a1rrk/nbO5amBda3

**Comment by JohnTHaller** [comment]
It runs on both 32-bit and 64-bit Windows 10, but the text in the speech boxes has an issue. The speaker is still there in yellow (Narrator, Edgar's Father, etc) but the spoken text is not. Likely it's black on the black background.

**Comment by riksweeney** [comment]
OK, I think I found the issue. Can you try the installer again? It's in the same link and called edgar32-1.33-2.installer.exe

**Comment by JohnTHaller** [comment]
The 1.33-2 package seems to be working as expected under Windows 10 32-bit and 64-bit

**Comment by riksweeney** [comment]
Great, thanks for letting me know. I'm going to close this issue now. Do let me know if you encounter any other graphical problems.
