### ISSUE TITLE
No text in some text fields

### ISSUE THREAD

**Issue by Sturwandan** [riksweeney/edgar#48]
This problem happens somewhat randomly. Sometimes text disappear in text boxes, sometimes it's shown. 
On a certain systems, namely archlinuxarm, the problem happens consistently and even the main menu cannot be read (though I don't have access to that at the moment).

Do you have any suggestion how to track the source of this problem down? It could be missing font, or black text on black background, I don't know.

@riksweeney have mentioned here https://github.com/riksweeney/edgar/issues/46#issuecomment-681781670 there was a solution to similar problem. Would be nice if he could share it, so I can test whenever I'm having same or different problem.

![no_fonts_edgar](https://user-images.githubusercontent.com/64779686/99905854-863f0080-2d0e-11eb-8c5b-8a18276f6b83.png)

**Comment by riksweeney** [comment]
This bug has been fixed, but there's no release available currently, I'm afraid.

**Comment by Sturwandan** [comment]
Alright, I have found the last commit which sets alpha channel like this:
`foregroundcolour.a = 255;`
`backgroundcolour.a = 255;`
I will try to insert it into `src/graphics/font.c` at several places where other channels are set and see if it works. Since I'm building from source, the easiest way is to insert this line:
`sed -e 's/\(\s*.\{4\}\groundcolour\.\).\?b.*/&\n\1a = 255;/' -i src/graphics/font.c`
Into the build script:
https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=legendofedgar
nearby the other sed expression, which edits makefile.

**P.S.** I have tried this on archlinuxarm, where even main menu was borked and the problem was solved! Thank you, @riksweeney
