### ISSUE TITLE
not really an issue :-)

### ISSUE THREAD

**Issue by timsoftgit** [riksweeney/edgar#59]
hi, I have created a Slackware package for the latest edgar (1.36). Since Slackware 15.0 there are no dependencies.
If you are interested I could send you it somehow. (approx. 129mb). Alternatively, the build script is at slackbuilds.org (i've just submitted the 1.36 update, so it should go live over the weekend.) you can run up a slackware vm, extract the slackbuild files with
`tar -xzf edgar.tar.gz` then place the source tar.gz in the same directory, and run edgar.SlackBuild  it will create the package in /tmp by default.
regards, Tim

**Comment by riksweeney** [comment]
Hi Tim,

Could you try copying the file to this Dropbox folder?

https://www.dropbox.com/request/xVtPrgt8XLC2bGJa4bT7

Hopefully this will work and not get flooded with junk from spambots :smiley:

**Comment by timsoftgit** [comment]
have done, thanks, although I just realised the SBo part of the filename should be changed to tjd  (I use sbopkg to build packages, but for general use/distribution of packages, the SBo should be changed to the packager initials) so the filename should be changed to `edgar-1.36-x86_64-1_tjd.tgz`
if you would like a 32bit package as well I can do one of those, but I would have to run up a 32bin vm, as I don't usually bother with pure 32bit any more, so it would take a day or so.

**Comment by riksweeney** [comment]
Great, thank you! I've added the file to the release now. I don't think there will be any need for a 32 bit version, I most likely won't build them going forward.
