### ISSUE TITLE
End of Golem fight is either buggy or really confusing

### ISSUE THREAD

**Issue by o11c** [riksweeney/edgar#7]
I've dropped 5 stones on the golem to reduce him to 0 HP. He's still rampaging, and nothing I do seems to do anything. The grabbers have moved to the center.

Stuff I've tried:
- Pick up and drop more rocks (one at a time or both together). They just pass through the golem and shatter.
- Use the pickaxe (while golem is shattered _or_ while moving). He regains HP on the first hit and again every time I reduce him to 0.

I'm using the package that just entered Debian (1.21-1), but the only newer upstream releases (1.22 and 1.23) only mention locale and packaging updates.

**Comment by riksweeney** [comment]
When he shatters, pick up the head with the grabbers.
